import Head from 'next/head'
import Image from 'next/image'
import styled from '@emotion/styled';

export default function Home() {
  return (
    <StyledHome>
      <Head>
        <title>Hike Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/e20sdfsd9.js" crossOrigin="anonymous"></script>
      </Head>
      {/* Background image */}
      <Image 
        src='/assets/home-bg.jpg'
        alt='background landing page image'
        className='home-bg-img'
        layout='fill'
        objectFit='cover'
        objectPosition='right'/>

      <main className='home-body'>
        <div className='home-welcome'>
          <h1>Hike Log</h1>
        </div>
      </main>

    </StyledHome>
  )
}

const StyledHome = styled.div`
  background: var(--bg-light-veil);
  color: var(--color-primary);

  .home-body {
    height: 100%;
    width: 100vw;
  }

  .home-welcome {
    position: absolute;
    top: 30%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: -1;
    width: 80%;
    text-align: center;
    font-size: 4rem;
  }
  
  .home-bg-img {
    z-index: 0;
    opacity: .7;
  }


`